dataset:
  name: "vcr"
  prompt: 0
  subset_size: -1
  data_path: "./data/vcr"
  modalities: ["image", "question", "answer"]
  types: ["image", "question", "answer","opitions","prompt"]
  url:
    vision: "https://visualcommonsense.com/"
    language: "https://visualcommonsense.com/"
    prompt: ""
task:
  name: "visual_question_answering"
  template_path: "./prompts/visual_question_answering/vcr-prompt-0/template.json"
  example_path: "./prompts/visual_question_answering/vcr-prompt-0/examples.json"
  definition: ""
  path: "https://okvqa.allenai.org/"
  input: ["text", "image","bbox_list"]
  output: ["answer"]
metadata:
  path: "./metadata/all_task.json"
output:
  path: "./tasks/"
contact:
  contributor: ["Anonymous"]