dataset:
  name: "vqa"
  prompt: 1
  subset_size: -1
  data_path: "./data/vqa"
  modalities: ["image", "text"]
  types: ["image", "question", "answer"]
  url:
    vision: "https://drive.google.com/drive/folders/1MBBhlkP83VMKS2Qe0SmFfzkHhMpIG5wf?usp=sharing"
    language: "https://drive.google.com/drive/folders/1MBBhlkP83VMKS2Qe0SmFfzkHhMpIG5wf?usp=sharing"
    prompt: "https://arxiv.org/pdf/2110.08484.pdf"
task:
  name: "visual_question_answering"
  template_path: "./prompts/visual_question_answering/vqa-prompt-1/template.json"
  example_path: "./prompts/visual_question_answering/vqa-prompt-1/examples.json"
  definition: ""
  path: "https://visualqa.org/"
  input: ["text", "image"]
  output: ["answer"]
metadata:
  path: "./metadata/all_task.json"
output:
  path: "./tasks/"
contact:
  contributor: ["Anonymous"]